<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title><?= $title ?></title>
  <link rel="stylesheet" type="text/css" href="style.css">
</head>

<body>
  <template id="loginFormTemplate">
    <h2>Login</h2>
    <form method="post" id="loginForm">
      <label for="username">User Name:</label>
      <input type="text" name="username" id="username">
      <label for="password">Password:</label>
      <input type="password" name="password" id="username">
  
      <button type="submit">Log in</button>
    </form>
    <p>Det här är en template som visar ett loginformulär</p>
  </template>
  
  <template id="registerFormTemplate">
    <h2>Register</h2>
    <form method="post">
      <label for="username">User Name:</label>
      <input type="text" name="username" id="username">
      <label for="password">Password:</label>
      <input type="password" name="password" id="username">

      <button type="submit">Log in</button>
    </form>

    <p>Det här är en template som visar ett registreringsformulär</p>
  </template>

  <div class="container">
    <header>
      <h1><?= $title ?></h1>
    </header>
    <main>
      <p>Hämta innehållet med hjälp av javascript. Har gjort loginFormTemplate och registerFormTemplate som ska hämtas. Nu ska vi skriva JS för att visa våra templates.</p>
    </main>
  </div>
  <script type="text/javascript" src="main.js"></script>
</body>

</html>
<!-- Lägg all html kod här -->