<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title><?= $title ?></title>
  <link rel="stylesheet" type="text/css" href="style.css">
  <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

</head>

<body>
  <header>
    <nav>

      <div class="nav-wrapper">
        <a href="" class="brand-logo">Home</a>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
          <li><a href="#showAllUsers">Show all friends</a></li>
          <li><a href="#allOurEntries">Show all posts</a></li>
        </ul>
      </div>

    </nav>
  </header>

  <div class="hero">
    <div class="hero-content">

      <h1>WELCOME TO OUR BLOG</h1>
      <h1><?= $title ?></h1>
      <form method="POST" id="searchValueForm">
        <div class="input-field">
          <input type="search" name="searchString" required>
          <label for="search">Search</label>
          <button type="submit">Search</button>
        </div>
      </form>

    </div>
  </div>

  <?php
  include('../src/views/templates/loggedInTemplate.php');
  include('../src/views/templates/loginErrorTemplate.php');
  include('../src/views/templates/loginFormTemplate.php');
  include('../src/views/templates/registeredTemplate.php');
  include('../src/views/templates/registerFormTemplate.php');
  include('../src/views/templates/allEntriesTemplate.php');
  include('../src/views/templates/createEntryTemplate.php');
  include('../src/views/templates/specificEntry.php');
  include('../src/views/templates/allUsersTemplate.php');
  include('../src/views/templates/allUsersBtnTemplate.php');
  include('../src/views/templates/specificComment.php');
  include('../src/views/templates/toggleTemplate.php');
  ?>
  <div class="container">

    <main>
    </main>
  </div>
  <footer class="page-footer">
    <div class="container">
      <div class="row">

        <div class="col l4 s12">
          <h5 class="white-text">Examination</h5>
          <ul>
            <li>Journal</li>
          </ul>
        </div>
        <div class="col l4 s12">
          <h5 class="white-text">Medlemmar</h5>
          <ul>
            <li>Emma Hägg</li>
            <li>Mikaela Johansson</li>
            <li>Ellinor Stenhaug</li>
          </ul>
        </div>
        <div class="col l4 s12">
          <h5 class="white-text">Gruppnamn</h5>
          <ul>
            <li>Untouchaballs</li>
          </ul>
        </div>
      </div>
    </div>
    <div class="footer-copyright">

    </div>
  </footer>
  <script type="text/javascript" src="js/bindevents.js"></script>

  <script type="text/javascript" src="js/main.js"></script>
  <script type="text/javascript" src="js/register.js"></script>
  <script type="text/javascript" src="js/login.js"></script>
  <script type="text/javascript" src="js/logout.js"></script>
  <script type="text/javascript" src="js/createEntry.js"></script>
  <script type="text/javascript" src="js/entries.js"></script>
  <script type="text/javascript" src="js/users.js"></script>
  <script type="text/javascript" src="js/createComment.js"></script>
  <script type="text/javascript" src="js/comments.js"></script>

  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

</body>

</html>